CBL_beta: 0.9999
Flag_CenterCrop: true
Flag_RamdomErasing: false
Flag_RandomHorizontalFlip: false
Flag_RandomResizedCrop: false
Flag_RandomRotation: false
Flag_RandomVerticalFlip: false
Flag_Resize_te: true
Flag_mGPU_blocks: false
List_mGPU_blocks:
- 0
- 1
alpha_center_loss: 0.001
batch_size: 32
config: ./config/r3d_18_scratch.yaml
data_root: /scratch/up1084667/MyThesis/DFEW_Dataset
data_type: single
degree_RandomRotation: 10
fold_idx: 2
gpu_id: 7
isconsecutive: false
loss_type: CEL
lr_gamma: 0.9
lr_init: 0.001
lr_strategy: true
model_init: true
model_name: r3d_18
model_pretrain: false
nframe: 16
num_classes: 7
num_epoch: 50
num_workers: 8
optimizer: Adam
pin_memory: true
pretrained_weights: None
prob_RandomErasing: 0.5
prob_RandomHorizontalFlip: 0.5
prob_RandomVerticalFlip: 0.5
saved_weights: None
scheduler: ExponentialLR
size_CenterCrop: 224
size_RandomResizedCrop: !!python/tuple
- 224
- 224
size_Resize_te: 112
step_size: 20
tensorboard: false
test_gap: epoch
test_stepLength: 100
test_ten_crop: false
torch_optimize: true
train_data_augment: false
txt_log: true
txt_log_toScreen: true
weight_decay: 0.0001
work_dir: ./work_dir/r3d_18_scratch_v2
y_start_from_zero: false
