# data path
data_type: "single"
data_root: "/scratch/up1084667/MyThesis/DFEW_Dataset"
work_dir: "./work_dir/r3d_18"

# speed: GPU and memory
gpu_id: 7
num_workers: 8
Flag_mGPU_blocks: False
List_mGPU_blocks: [0, 1] 

# Input Settings
nframe: 16              
size_Resize_te: 112    
num_epoch: 30
batch_size: 32

# Model Settings
model_pretrain: True
model_init: False

loss_type: "CEL"

# Optimizer & Scheduler
optimizer: "SGD"        # Το SGD είναι καλύτερο για ResNets από τον Adam
lr_init: 0.001           
weight_decay: 0.0005
lr_strategy: True
scheduler: "StepLR"
step_size: 10           # Μείωση κάθε 10 εποχές
lr_gamma: 0.1

# Augmentation Flags (Ρυθμισμένα για 112x112)
train_data_augment: True
Flag_RandomRotation: True
degree_RandomRotation: 10

Flag_RandomResizedCrop: True
size_RandomResizedCrop: 112    

Flag_RandomHorizontalFlip: True
prob_RandomHorizontalFlip: 0.5
Flag_RandomVerticalFlip: False
Flag_CenterCrop: False
size_CenterCrop: 112       
Flag_RamdomErasing: False
prob_RandomErasing: 0.
Flag_Resize_te: True